[[nav]]
    name = "Knowledge Base"
    url = "/knowledge-base/"
    weight = 1

[[nav]]
    name = "Blog"
    url = "/blog/"
    weight = 2

[[nav]]
    name = "awesome-pion"
    url = "https://github.com/pion/awesome-pion"
    weight = 3

